export enum ProcessStage {
  SELECT = 'SELECT',
  REVIEW = 'REVIEW',
}

export enum ComplianceUseCase {
  PURGE_BIN = 'PURGE_BIN',
  CASH_LOAD = 'CASH_LOAD',
  TRAFFIC_LIGHT = 'TRAFFIC_LIGHT',
  RECEIPT_ROLL = 'RECEIPT_ROLL',
  CASSETE_SEAL = 'CASSETE_SEAL',
  WINCOR_STATUS_CODE = 'WINCOR_STATUS_CODE',
  MACHINE_IN_SERVICE_OSS = 'MACHINE_IN_SERVICE_OSS',
}
